# Generated by Django 5.0.1 on 2024-10-07 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('is_pne', models.BooleanField(default=False)),
                ('is_idoso', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=5)),
                ('tipo', models.CharField(choices=[('DUPLA', 'Vaga Dupla'), ('LIVRE', 'Vaga Livre')], max_length=6)),
                ('especial', models.CharField(choices=[('NORMAL', 'Normal'), ('PNE', 'PNE'), ('IDOSO', 'Idoso')], default='NORMAL', max_length=6)),
                ('subsolo', models.IntegerField(choices=[(1, 'Subsolo 1'), (2, 'Subsolo 2')])),
                ('is_livre_quando_nao_especial', models.BooleanField(default=True)),
                ('dupla_com', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dupla', to='tres_coelhos.vaga')),
            ],
        ),
        migrations.CreateModel(
            name='Sorteio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_sorteio', models.DateTimeField(auto_now_add=True)),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tres_coelhos.apartamento')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tres_coelhos.vaga')),
            ],
        ),
        migrations.CreateModel(
            name='DuplaSorteio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_sorteio', models.DateTimeField(auto_now_add=True)),
                ('apartamento_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dupla_apartamento_1', to='tres_coelhos.apartamento')),
                ('apartamento_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dupla_apartamento_2', to='tres_coelhos.apartamento')),
                ('vaga_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaga_1', to='tres_coelhos.vaga')),
                ('vaga_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaga_2', to='tres_coelhos.vaga')),
            ],
        ),
    ]
