# Generated by Django 5.0.1 on 2024-10-07 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tres_coelhos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duplasorteio',
            name='apartamento_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dupla_apartamento_sorteio_1', to='tres_coelhos.apartamento'),
        ),
        migrations.AlterField(
            model_name='duplasorteio',
            name='apartamento_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dupla_apartamento_sorteio_2', to='tres_coelhos.apartamento'),
        ),
        migrations.AlterField(
            model_name='duplasorteio',
            name='vaga_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaga_sorteio_1', to='tres_coelhos.vaga'),
        ),
        migrations.AlterField(
            model_name='duplasorteio',
            name='vaga_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaga_sorteio_2', to='tres_coelhos.vaga'),
        ),
        migrations.CreateModel(
            name='DuplaApartamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('apartamento_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dupla_apartamento_pre_1', to='tres_coelhos.apartamento')),
                ('apartamento_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dupla_apartamento_pre_2', to='tres_coelhos.apartamento')),
            ],
        ),
    ]
