# Generated by Django 5.0.1 on 2024-10-08 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tres_coelhos', '0002_alter_duplasorteio_apartamento_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SorteioDupla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_sorteio', models.DateTimeField(auto_now_add=True)),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tres_coelhos.apartamento')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tres_coelhos.vaga')),
            ],
        ),
        migrations.DeleteModel(
            name='DuplaSorteio',
        ),
    ]
