# Generated by Django 5.0.1 on 2024-10-08 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tres_coelhos', '0003_sorteiodupla_delete_duplasorteio'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorteiodupla',
            name='vaga_dupla_com',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaga_dupla_sorteada_com', to='tres_coelhos.vaga'),
        ),
    ]
