# Generated by Django 5.0.1 on 2024-05-07 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApartamentoTorre1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_apartamento', models.CharField(max_length=50)),
                ('presenca', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VagaTorre1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaga', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SorteioTorre1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='helbor.apartamentotorre1')),
                ('vaga', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='helbor.vagatorre1')),
            ],
        ),
    ]
