# Generated by Django 5.0.1 on 2024-05-07 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helbor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartamentotorre1',
            name='presenca',
        ),
    ]
