# Generated by Django 5.0.1 on 2024-05-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helbor', '0002_remove_apartamentotorre1_presenca'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartamentotorre1',
            name='pcd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vagatorre1',
            name='pcd',
            field=models.BooleanField(default=False),
        ),
    ]
