# Generated by Django 5.0.1 on 2024-05-08 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helbor', '0003_apartamentotorre1_pcd_vagatorre1_pcd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartamentotorre1',
            name='pcd',
        ),
        migrations.RemoveField(
            model_name='vagatorre1',
            name='pcd',
        ),
    ]
