# Generated by Django 5.0.1 on 2024-05-09 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helbor', '0004_remove_apartamentotorre1_pcd_remove_vagatorre1_pcd'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartamentoTorre2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_apartamento', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VagaTorre2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaga', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SorteioTorre2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='helbor.apartamentotorre1')),
                ('vaga', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='helbor.vagatorre1')),
            ],
        ),
    ]
