# Generated by Django 5.0.1 on 2024-02-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assincon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaSindicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
            ],
        ),
    ]
