# Generated by Django 5.0.1 on 2024-02-27 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assincon', '0002_listasindicos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sorteio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorteado', models.BooleanField(default=False)),
                ('sindico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assincon.listasindicos')),
            ],
        ),
    ]
