# Generated by Django 5.0.1 on 2024-04-23 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assincon', '0003_sorteio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListaPresenca',
        ),
    ]
