# Generated by Django 5.0.1 on 2024-05-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='pcd',
            field=models.BooleanField(default=False),
        ),
    ]
