# Generated by Django 5.0.1 on 2024-05-02 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyon', '0002_vaga_pcd'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartamentoMoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_apartamento', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VagaMoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaga', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SorteioMoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lyon.apartamento')),
                ('vaga', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lyon.vaga')),
            ],
        ),
    ]
