# Generated by Django 5.0.1 on 2024-05-02 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyon', '0003_apartamentomoto_vagamoto_sorteiomoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorteiomoto',
            name='apartamento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lyon.apartamentomoto'),
        ),
        migrations.AlterField(
            model_name='sorteiomoto',
            name='vaga',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lyon.vagamoto'),
        ),
    ]
