# Generated by Django 5.0.1 on 2024-10-14 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sky_view', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartamento',
            name='andar',
        ),
    ]
