# Generated by Django 5.0.1 on 2024-10-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sky_view', '0002_remove_apartamento_andar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='numero',
            field=models.CharField(max_length=20),
        ),
    ]
