# Generated by Django 5.0.1 on 2024-10-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sky_view', '0003_alter_vaga_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='subsolo',
            field=models.CharField(choices=[('Térreo', 'Térreo'), ('1º Subsolo', '1º Subsolo'), ('2º Subsolo', '2º Subsolo'), ('3º Subsolo', '3º Subsolo'), ('4º Subsolo', '4º Subsolo')], max_length=10),
        ),
    ]
