# Generated by Django 5.0.1 on 2024-10-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sky_view', '0004_alter_vaga_subsolo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='tipo_vaga',
            field=models.CharField(choices=[('Simples', 'Simples'), ('Dupla', 'Dupla')], max_length=10),
        ),
    ]
