# Generated by Django 5.0.1 on 2024-02-20 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_apartamento', models.CharField(choices=[('Apto 101', 'Apto 101'), ('Apto 102', 'Apto 102'), ('Apto 103', 'Apto 103'), ('Apto 104', 'Apto 104'), ('Apto 201', 'Apto 201'), ('Apto 202', 'Apto 202'), ('Apto 203', 'Apto 203'), ('Apto 204', 'Apto 204'), ('Apto 301', 'Apto 301'), ('Apto 302', 'Apto 302'), ('Apto 303', 'Apto 303'), ('Apto 304', 'Apto 304'), ('Apto 401', 'Apto 401'), ('Apto 402', 'Apto 402'), ('Apto 403', 'Apto 403'), ('Apto 404', 'Apto 404'), ('Apto 501', 'Apto 501'), ('Apto 502', 'Apto 502'), ('Apto 503', 'Apto 503'), ('Apto 504', 'Apto 504'), ('Apto 601', 'Apto 601'), ('Apto 602', 'Apto 602'), ('Apto 603', 'Apto 603'), ('Apto 604', 'Apto 604'), ('Apto 701', 'Apto 701'), ('Apto 702', 'Apto 702'), ('Apto 703', 'Apto 703'), ('Apto 704', 'Apto 704'), ('Apto 801', 'Apto 801'), ('Apto 802', 'Apto 802'), ('Apto 803', 'Apto 803'), ('Apto 804', 'Apto 804'), ('Apto 901', 'Apto 901'), ('Apto 902', 'Apto 902'), ('Apto 903', 'Apto 903'), ('Apto 904', 'Apto 904'), ('Apto 1001', 'Apto 1001'), ('Apto 1002', 'Apto 1002'), ('Apto 1003', 'Apto 1003'), ('Apto 1004', 'Apto 1004'), ('Apto 1101', 'Apto 1101'), ('Apto 1102', 'Apto 1102'), ('Apto 1103', 'Apto 1103'), ('Apto 1104', 'Apto 1104'), ('Apto 1201', 'Apto 1201'), ('Apto 1202', 'Apto 1202'), ('Apto 1203', 'Apto 1203'), ('Apto 1204', 'Apto 1204'), ('Apto 1301', 'Apto 1301'), ('Apto 1302', 'Apto 1302'), ('Apto 1303', 'Apto 1303'), ('Apto 1304', 'Apto 1304'), ('Apto 1401', 'Apto 1401'), ('Apto 1402', 'Apto 1402'), ('Apto 1403', 'Apto 1403'), ('Apto 1404', 'Apto 1404')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoVaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vagas', models.CharField(choices=[('Vaga 01, Vaga 10 e Vaga 11', 'Vaga 01, Vaga 10 e Vaga 11'), ('Vaga 02, Vaga 12 e Vaga 13', 'Vaga 02, Vaga 12 e Vaga 13'), ('Vaga 03, Vaga 17 e Vaga 18', 'Vaga 03, Vaga 17 e Vaga 18'), ('Vaga 04, Vaga 19 e Vaga 20', 'Vaga 04, Vaga 19 e Vaga 20'), ('Vaga 05, Vaga 21 e Vaga 22', 'Vaga 05, Vaga 21 e Vaga 22'), ('Vaga 06, Vaga 23 e Vaga 24', 'Vaga 06, Vaga 23 e Vaga 24'), ('Vaga 07, Vaga 25 e Vaga 26', 'Vaga 07, Vaga 25 e Vaga 26'), ('Vaga 08, Vaga 27 e Vaga 28', 'Vaga 08, Vaga 27 e Vaga 28'), ('Vaga 09, Vaga 29 e Vaga 30', 'Vaga 09, Vaga 29 e Vaga 30'), ('Vaga 14, Vaga 31 e Vaga 32', 'Vaga 14, Vaga 31 e Vaga 32'), ('Vaga 15, Vaga 33 e Vaga 34', 'Vaga 15, Vaga 33 e Vaga 34'), ('Vaga 35, Vaga 36 e Vaga 37', 'Vaga 35, Vaga 36 e Vaga 37'), ('Vaga 38, Vaga 39 e Vaga 40', 'Vaga 38, Vaga 39 e Vaga 40'), ('Vaga 41, Vaga 42 e Vaga 43', 'Vaga 41, Vaga 42 e Vaga 43'), ('Vaga 44, Vaga 45 e Vaga 46', 'Vaga 44, Vaga 45 e Vaga 46'), ('Vaga 47, Vaga 56 e Vaga 57', 'Vaga 47, Vaga 56 e Vaga 57'), ('Vaga 48, Vaga 58 e Vaga 59', 'Vaga 48, Vaga 58 e Vaga 59'), ('Vaga 49, Vaga 50 e Vaga 51', 'Vaga 49, Vaga 50 e Vaga 51'), ('Vaga 52, Vaga 53 e Vaga 54', 'Vaga 52, Vaga 53 e Vaga 54'), ('Vaga 55, Vaga 60 e Vaga 61', 'Vaga 55, Vaga 60 e Vaga 61'), ('Vaga 62, Vaga 64 e Vaga 66', 'Vaga 62, Vaga 64 e Vaga 66'), ('Vaga 63, Vaga 65 e Vaga 67', 'Vaga 63, Vaga 65 e Vaga 67'), ('Vaga 79, Vaga 68 e Vaga 69', 'Vaga 79, Vaga 68 e Vaga 69'), ('Vaga 80, Vaga 70 e Vaga 71', 'Vaga 80, Vaga 70 e Vaga 71'), ('Vaga 81, Vaga 72 e Vaga 73', 'Vaga 81, Vaga 72 e Vaga 73'), ('Vaga 82, Vaga 74 e Vaga 75', 'Vaga 82, Vaga 74 e Vaga 75'), ('Vaga 83, Vaga 84 e Vaga 85', 'Vaga 83, Vaga 84 e Vaga 85'), ('Vaga 86, Vaga 87 e Vaga 88', 'Vaga 86, Vaga 87 e Vaga 88'), ('Vaga 76, Vaga 77 e Vaga 78', 'Vaga 76, Vaga 77 e Vaga 78'), ('Vaga 89, Vaga 90 e Vaga 91', 'Vaga 89, Vaga 90 e Vaga 91'), ('Vaga 92, Vaga 102 e Vaga 103', 'Vaga 92, Vaga 102 e Vaga 103'), ('Vaga 93, Vaga 104 e Vaga 105', 'Vaga 93, Vaga 104 e Vaga 105'), ('Vaga 94, Vaga 95 e Vaga 96', 'Vaga 94, Vaga 95 e Vaga 96'), ('Vaga 97, Vaga 98 e Vaga 99', 'Vaga 97, Vaga 98 e Vaga 99'), ('Vaga 100, Vaga 101 e Vaga 106', 'Vaga 100, Vaga 101 e Vaga 106'), ('Vaga 107, Vaga 125 e Vaga 126', 'Vaga 107, Vaga 125 e Vaga 126'), ('Vaga 108, Vaga 110 e Vaga 112', 'Vaga 108, Vaga 110 e Vaga 112'), ('Vaga 109, Vaga 111 e Vaga 113', 'Vaga 109, Vaga 111 e Vaga 113'), ('Vaga 127, Vaga 114 e Vaga 115', 'Vaga 127, Vaga 114 e Vaga 115'), ('Vaga 128, Vaga 116 e Vaga 117', 'Vaga 128, Vaga 116 e Vaga 117'), ('Vaga 129, Vaga 118 e Vaga 119', 'Vaga 129, Vaga 118 e Vaga 119'), ('Vaga 130, Vaga 120 e Vaga 121', 'Vaga 130, Vaga 120 e Vaga 121'), ('Vaga 131, Vaga 132 e Vaga 133', 'Vaga 131, Vaga 132 e Vaga 133'), ('Vaga 134, Vaga 135 e Vaga 136', 'Vaga 134, Vaga 135 e Vaga 136'), ('Vaga 122, Vaga 123 e Vaga 124', 'Vaga 122, Vaga 123 e Vaga 124'), ('Vaga 139, Vaga 137 e Vaga 138', 'Vaga 139, Vaga 137 e Vaga 138'), ('Vaga 140, Vaga 157 e Vaga 158', 'Vaga 140, Vaga 157 e Vaga 158'), ('Vaga 141, Vaga 143 e Vaga 145', 'Vaga 141, Vaga 143 e Vaga 145'), ('Vaga 142, Vaga 144 e Vaga 146', 'Vaga 142, Vaga 144 e Vaga 146'), ('Vaga 159, Vaga 160 e Vaga 161', 'Vaga 159, Vaga 160 e Vaga 161'), ('Vaga 16, Vaga 162 e Vaga 163', 'Vaga 16, Vaga 162 e Vaga 163'), ('Vaga 164, Vaga 147 e Vaga 148', 'Vaga 164, Vaga 147 e Vaga 148'), ('Vaga 165, Vaga 149 e Vaga 150', 'Vaga 165, Vaga 149 e Vaga 150'), ('Vaga 166, Vaga 151 e Vaga 152', 'Vaga 166, Vaga 151 e Vaga 152'), ('Vaga 167, Vaga 153 e Vaga 154', 'Vaga 167, Vaga 153 e Vaga 154'), ('Vaga 168, Vaga 155 e Vaga 156', 'Vaga 168, Vaga 155 e Vaga 156')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sorteio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nova_colina.apartamento')),
                ('vagas', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nova_colina.grupovaga')),
            ],
        ),
    ]
