# Generated by Django 5.0.1 on 2024-02-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListaDePresenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartamento', models.CharField(choices=[('Apto 01', 'apartamento 01'), ('Apto 02', 'apartamento 02'), ('Apto 03', 'apartamento 03'), ('Apto 04', 'apartamento 04'), ('Apto 05', 'apartamento 05')], max_length=100)),
                ('bloco', models.CharField(default='-', max_length=100)),
                ('presenca', models.BooleanField(default=False, null=True)),
                ('vaga', models.CharField(blank=True, choices=[('Vaga 01', 'Vaga 01'), ('Vaga 02', 'Vaga 02'), ('Vaga 03', 'Vaga 03'), ('Vaga 04', 'Vaga 04'), ('Vaga 05', 'Vaga 05')], max_length=100, null=True)),
            ],
        ),
    ]
