# Generated by Django 5.0.1 on 2024-07-03 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('max_club', '0002_apartamentobike_vagabike_sorteiobike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorteiobike',
            name='apartamento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='max_club.apartamentobike'),
        ),
        migrations.AlterField(
            model_name='sorteiobike',
            name='vaga',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='max_club.vagabike'),
        ),
    ]
