# Generated by Django 5.0.1 on 2024-02-20 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloco', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaga', models.CharField(choices=[('Vaga 01', 'Vaga 01'), ('Vaga 02', 'Vaga 02'), ('Vaga 03', 'Vaga 03'), ('Vaga 04', 'Vaga 04'), ('Vaga 05', 'Vaga 05'), ('Vaga 06', 'Vaga 06'), ('Vaga 07', 'Vaga 07'), ('Vaga 08', 'Vaga 08'), ('Vaga 09', 'Vaga 09'), ('Vaga 10', 'Vaga 10'), ('Vaga 11', 'Vaga 11'), ('Vaga 12', 'Vaga 12'), ('Vaga 13', 'Vaga 13'), ('Vaga 14', 'Vaga 14'), ('Vaga 15', 'Vaga 15'), ('Vaga 16', 'Vaga 16'), ('Vaga 17', 'Vaga 17'), ('Vaga 18', 'Vaga 18'), ('Vaga 19', 'Vaga 19'), ('Vaga 20', 'Vaga 20'), ('Vaga 21', 'Vaga 21'), ('Vaga 22', 'Vaga 22'), ('Vaga 23', 'Vaga 23'), ('Vaga 24', 'Vaga 24'), ('Vaga 25', 'Vaga 25'), ('Vaga 26', 'Vaga 26'), ('Vaga 27', 'Vaga 27'), ('Vaga 28', 'Vaga 28'), ('Vaga 29', 'Vaga 29'), ('Vaga 30', 'Vaga 30'), ('Vaga 31', 'Vaga 31'), ('Vaga 32', 'Vaga 32'), ('Vaga 33', 'Vaga 33'), ('Vaga 34', 'Vaga 34'), ('Vaga 35', 'Vaga 35'), ('Vaga 36', 'Vaga 36'), ('Vaga 37', 'Vaga 37'), ('Vaga 38', 'Vaga 38'), ('Vaga 39', 'Vaga 39'), ('Vaga 40', 'Vaga 40'), ('Vaga 41', 'Vaga 41'), ('Vaga 42', 'Vaga 42'), ('Vaga 43', 'Vaga 43'), ('Vaga 44', 'Vaga 44'), ('Vaga 45', 'Vaga 45'), ('Vaga 46', 'Vaga 46'), ('Vaga 47', 'Vaga 47'), ('Vaga 48', 'Vaga 48'), ('Vaga 49', 'Vaga 49'), ('Vaga 50', 'Vaga 50')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_apartamento', models.CharField(choices=[('Apto 01', 'Apto 01'), ('Apto 02', 'Apto 02'), ('Apto 11', 'Apto 11'), ('Apto 12', 'Apto 12'), ('Apto 13', 'Apto 13'), ('Apto 14', 'Apto 14'), ('Apto 15', 'Apto 15'), ('Apto 16', 'Apto 16'), ('Apto 21', 'Apto 21'), ('Apto 22', 'Apto 22'), ('Apto 23', 'Apto 23'), ('Apto 24', 'Apto 24'), ('Apto 25', 'Apto 25'), ('Apto 26', 'Apto 26'), ('Apto 31', 'Apto 31'), ('Apto 32', 'Apto 32'), ('Apto 33', 'Apto 33'), ('Apto 34', 'Apto 34'), ('Apto 35', 'Apto 35'), ('Apto 36', 'Apto 36'), ('Apto 41', 'Apto 41'), ('Apto 42', 'Apto 42'), ('Apto 43', 'Apto 43'), ('Apto 44', 'Apto 44'), ('Apto 45', 'Apto 45'), ('Apto 46', 'Apto 46')], max_length=50)),
                ('bloco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chacara_bom_sucesso.bloco')),
            ],
            options={
                'unique_together': {('numero_apartamento', 'bloco')},
            },
        ),
        migrations.CreateModel(
            name='Sorteio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chacara_bom_sucesso.apartamento')),
                ('vaga', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chacara_bom_sucesso.vaga')),
            ],
        ),
    ]
