# Generated by Django 5.0.1 on 2024-02-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chacara_bom_sucesso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='vaga',
            field=models.CharField(choices=[('Vaga 01 Bloco B', 'Vaga 01 Bloco B'), ('Vaga 02 Bloco B', 'Vaga 02 Bloco B'), ('Vaga 03 Bloco B', 'Vaga 03 Bloco B'), ('Vaga 04 Bloco B', 'Vaga 04 Bloco B'), ('Vaga 05 Bloco B', 'Vaga 05 Bloco B'), ('Vaga 06 Bloco B', 'Vaga 06 Bloco B'), ('Vaga 07 Bloco B', 'Vaga 07 Bloco B'), ('Vaga 08 Bloco B', 'Vaga 08 Bloco B'), ('Vaga 09 Bloco B', 'Vaga 09 Bloco B'), ('Vaga 10 Bloco B', 'Vaga 10 Bloco B'), ('Vaga 11 Bloco B', 'Vaga 11 Bloco B'), ('Vaga 12 Bloco B', 'Vaga 12 Bloco B'), ('Vaga 13 Bloco B', 'Vaga 13 Bloco B'), ('Vaga 14 Bloco B', 'Vaga 14 Bloco B'), ('Vaga 15 Bloco B', 'Vaga 15 Bloco B'), ('Vaga 16 Bloco B', 'Vaga 16 Bloco B'), ('Vaga 17 Bloco B', 'Vaga 17 Bloco B'), ('Vaga 18 Bloco B', 'Vaga 18 Bloco B'), ('Vaga 19 Bloco B', 'Vaga 19 Bloco B'), ('Vaga 20 Bloco B', 'Vaga 20 Bloco B'), ('Vaga 21 Bloco B', 'Vaga 21 Bloco B'), ('Vaga 22 Bloco B', 'Vaga 22 Bloco B'), ('Vaga 23 Bloco B', 'Vaga 23 Bloco B'), ('Vaga 24 Bloco B', 'Vaga 24 Bloco B'), ('Vaga 25 Bloco B', 'Vaga 25 Bloco B'), ('Vaga 26 Bloco B', 'Vaga 26 Bloco B'), ('Vaga 27 Bloco A', 'Vaga 27 Bloco A'), ('Vaga 28 Bloco A', 'Vaga 28 Bloco A'), ('Vaga 29 Bloco A', 'Vaga 29 Bloco A'), ('Vaga 30 Bloco A', 'Vaga 30 Bloco A'), ('Vaga 31 Bloco A', 'Vaga 31 Bloco A'), ('Vaga 32 Bloco A', 'Vaga 32 Bloco A'), ('Vaga 33 Bloco A', 'Vaga 33 Bloco A'), ('Vaga 34 Bloco A', 'Vaga 34 Bloco A'), ('Vaga 35 Bloco A', 'Vaga 35 Bloco A'), ('Vaga 36 Bloco A', 'Vaga 36 Bloco A'), ('Vaga 37 Bloco A', 'Vaga 37 Bloco A'), ('Vaga 38 Bloco A', 'Vaga 38 Bloco A'), ('Vaga 39 Bloco A', 'Vaga 39 Bloco A'), ('Vaga 40 Bloco A', 'Vaga 40 Bloco A'), ('Vaga 41 Bloco A', 'Vaga 41 Bloco A'), ('Vaga 42 Bloco A', 'Vaga 42 Bloco A'), ('Vaga 43 Bloco A', 'Vaga 43 Bloco A'), ('Vaga 44 Bloco A', 'Vaga 44 Bloco A'), ('Vaga 45 Bloco A', 'Vaga 45 Bloco A'), ('Vaga 46 Bloco A', 'Vaga 46 Bloco A'), ('Vaga 47 Bloco A', 'Vaga 47 Bloco A'), ('Vaga 48 Bloco A', 'Vaga 48 Bloco A'), ('Vaga 49 Bloco A', 'Vaga 49 Bloco A'), ('Vaga 50 Bloco A', 'Vaga 50 Bloco A')], max_length=50, unique=True),
        ),
    ]
