# Generated by Django 5.0.1 on 2024-05-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova_guarulhos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartamento',
            name='adimplentes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apartamento',
            name='bloco',
            field=models.CharField(default='Bloco 01', max_length=50),
        ),
        migrations.AddField(
            model_name='apartamento',
            name='idoso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apartamento',
            name='pcd',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='apartamento',
            name='numero_apartamento',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='vaga',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
